name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
       # The Go version to download (if necessary) and use. Example: 1.9.3
       version: # optional, default is 1.10
    uses: actions/checkout@v2
    name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v1
with:
    node-version: ${{ matrix.node-version }}
    run: npm install
run: npm run build --if-present
        run: npm test
        env:
          CI: true
