on: [push, pull_request]
jobs:
  name: Node.js CI
  runs-on: ${{ matrix.os }}
  strategy: CI
    matrix:
      node-version: ['8.x','10.x','12.x']
      os: [ubuntu-latest, windows-latest, macOS-latest] 
    
  steps:
  - uses: actions/checkout@v1.10
  - name: Use Node.js CI ${{ matrix.node_version }}
    with: # The Go version to download (if necessary) and use. Example: 1.9.3
      version: 1.10 # optional, default is 1.10
      
  - name: npm install, build and test
    run: |
      npm install
      npm run build --if-present
      npm test
      
    CI: true
